import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import HeaderPage from "./components/header";
import Navbar from "./components/Navbar";
import MainNavbar from "./components/MainNavbar";
import Footer from "./components/footer";
import { GlobalProvider } from "./components/GlobleProvider";
import { CartProvider } from "./context/CartContaxt";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider>
            <HeaderPage />
            <Navbar />
            <MainNavbar />
        {children}
        <Footer />
          </CartProvider>
        </body>
    </html>
  );
}